ПРАКТИЧНА РОБОТА 1.
Вступ до машинного навчання. Елементи лінійної алгебри.


Номер варіанту 21

1.	Створіть одновимірний масив (вектор) зі значеннями натуральних чисел, починаючи з 1, та виведіть його значення.

In [1]:
import numpy as np

In [2]:
v1= np.arange(1,15)
print(v1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


2.	Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його косинусами кожного натурального числа, починаючи з 1, та виведіть його значення.

In [3]:
M=np.cos(np.arange(1,10).reshape(3,3))
print (M)

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


3.	Створіть масив розміром 7x7, заповніть його випадковими цілими числами від -50 до 50 та знайдіть відсоток непарних чисел серед додатних елементів

In [4]:
M=np.random.randint(-50,50,size=(7,7))
positive = M[M>0]
NeparPositive = positive[positive %2 !=0]
vidsotok = (len(NeparPositive) / len(positive)) * 100
print("{:.2f}%".format(vidsotok))

54.55%


4.	Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від -0.7 до 0.7 та виведіть його значення.

In [5]:
M = np.random.uniform(-0.7,0.7, size = (4,4))
print (M)

[[ 0.3765218   0.216772   -0.62738227  0.44191392]
 [-0.19834121  0.68373509 -0.59563366  0.0491373 ]
 [ 0.4803664   0.68458836 -0.12928278 -0.34204049]
 [ 0.64503053  0.21287553 -0.00788864 -0.63124241]]


5.	Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 10 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [6]:
A = np.random.randint(10,20, size= (5))
B = np.random.randint(10,20, size= (5))
print (A)
print (B)
print (A+B)
print (A-B)
print (A*B)

[19 19 12 11 18]
[14 14 18 16 15]
[33 33 30 27 33]
[ 5  5 -6 -5  3]
[266 266 216 176 270]


6.	Створіть два вектори розміром 6, заповніть їх довільними дійсними числами та знайдіть їх скалярний добуток.

In [7]:
list1= np.random.uniform(1,10 ,size=(6))
list2= np.random.uniform(1,10 ,size=(6))
v1= np.array(list1)
v2= np.array(list2)
ScalDob= np.dot(v1,v2)
print (ScalDob)

159.56561307832663


7.	Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [8]:
M1= np.random.randint(1,10, size=(2,3))
M2= np.random.randint(1,10, size=(3,3))
result = np.dot(M1,M2)
print(result)

[[ 68 116 129]
 [ 53  95 116]]


8.	Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю

In [9]:
M1= np.random.randint(1,12, size= (2,2))
reverse= np.linalg.inv(M1)
print (M1)
print(reverse)

[[8 3]
 [1 8]]
[[ 0.13114754 -0.04918033]
 [-0.01639344  0.13114754]]


9.	Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [10]:
M1= np.random.uniform(0,1, size=(3,3))
trans= np.transpose(M1)
print (M1)
print (trans)

[[0.96178603 0.85851325 0.72269663]
 [0.72596643 0.04138607 0.81422858]
 [0.64659353 0.84462384 0.65029768]]
[[0.96178603 0.72596643 0.64659353]
 [0.85851325 0.04138607 0.84462384]
 [0.72269663 0.81422858 0.65029768]]


10.	Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [11]:
M1 = np.random.randint(1,11, size=(3,4))
list1 = np.random.uniform(0,1, size= (4))
V1 = np.array(list1)
print (M1)
print (V1)
res= np.dot(M1,V1)
print(res)


[[7 9 4 4]
 [9 6 6 2]
 [2 1 2 2]]
[0.63541036 0.93401299 0.70533463 0.70195635]
[18.48315332 16.95869163  5.01941566]


11.	Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [12]:
M1 = np.random.uniform(0,1, size=(2,3))
List1 = np.random.randint(1,10, size=(3))
V1=np.array(List1)
dob= np.dot(M1,List1)
print (M1)
print (V1)
print (dob)

[[0.97723586 0.18443612 0.62297518]
 [0.21937685 0.97324521 0.50816692]]
[2 7 4]
[5.73742526 9.28413784]


12.	Створіть дві матриці розміром 6x6, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму всіх елементів першої матриці.

In [13]:
M1= np.random.randint(1,10, size=(6,6))
M2= np.random.randint(1,10, size=(6,6))
sum= np.sum(M1)
print (M1)
print ("Сума (чомусь неправильно рахується) =", sum)

[[2 6 8 4 5 1]
 [5 7 7 1 4 8]
 [2 4 5 3 9 2]
 [9 4 3 9 4 7]
 [1 3 3 5 3 9]
 [2 1 5 1 8 4]]
Сума (чомусь неправильно рахується) = 164


13.	Створіть дві матриці розміром 5x5, заповніть їх випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть добуток їх елементів.

In [14]:
M1 = np.random.uniform(-2,2, size = (5,5))
M2 = np.random.uniform(-2,2, size = (5,5))
dob= np.multiply(M1,M2)
print(M1)
print(M2)
print(dob)

[[-0.30751241 -1.39615246  0.81497489 -0.14244108  0.86689722]
 [-1.1679541   1.85622836 -0.530242    0.15367532 -1.91550769]
 [ 0.25316521 -0.77662929  1.6294801   0.81891574 -0.70063188]
 [ 0.01710677  1.31955068 -0.41143427 -0.06559252  1.39886708]
 [ 1.96713445 -1.43013249  0.83660934 -1.03211653  1.4225751 ]]
[[ 0.05245493  1.98342595 -0.9976074  -1.62749685  1.31338472]
 [-0.93173272  1.3484024   1.41885137  0.7915921  -1.10534333]
 [-1.02882022 -1.19805235  1.39375423  1.68710226  1.07118067]
 [ 1.3982702  -0.1624854   0.74034577  1.12676694 -1.35266606]
 [ 0.98861587 -0.36418981 -1.73795562  0.49294811 -1.75950302]]
[[-0.01613054 -2.76916501 -0.81302498  0.23182241  1.13856956]
 [ 1.08822105  2.50294278 -0.75233459  0.12164817  2.11729366]
 [-0.26046149  0.93044254  2.27109478  1.38159459 -0.75050332]
 [ 0.02391989 -0.21440772 -0.30460362 -0.07390749 -1.89220003]
 [ 1.94474034  0.52083968 -1.4539899  -0.5087799  -2.50302517]]


14.	Створіть матрицю розміром 7x7, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть найменший елемент матриці.

In [15]:
M1= np.random.uniform(-10,10, size=(7,7))
min = np.min(M1)
print(M1)
print(min)

[[ 9.65822174  4.87391441 -5.08385281 -4.53883739 -4.89476126  9.59012578
  -5.66607672]
 [ 5.80020584  3.6460801  -3.95505604 -0.56793513  8.8304755   1.6399995
  -6.97620075]
 [ 4.02389229 -6.24460368  5.11461297  3.90414756  8.48729981 -5.61939464
  -5.53850706]
 [ 3.87511547  4.45193314 -8.97824261  1.43146457  2.25638257  7.28012341
  -5.38205272]
 [ 6.11840446  2.39161099 -7.19921222 -8.30197845 -4.04904616 -8.74939703
  -5.74456452]
 [-2.23551314 -7.82777097  3.51372983 -2.93355752  9.74832683  5.49386167
  -7.86896848]
 [ 4.61263205  5.30817797  4.4956536   1.00064161 -8.63115412  0.83186707
   6.2577648 ]]
-8.978242605403269


15.	Створіть матрицю розміром 7x7, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного стовпця матриці.

In [16]:
M1= np.random.uniform(0,1, size=(7,7))
sum= np.sum(M1, axis=0)
print("матриця:")
print (M1)
print("сума стовпчиків матриці")
print (sum)


матриця:
[[0.59705717 0.82072168 0.50150609 0.27600568 0.13144626 0.1862502
  0.66030463]
 [0.50853515 0.59569968 0.90284382 0.67121458 0.37570181 0.72987813
  0.52503111]
 [0.79619648 0.62730337 0.97468222 0.44474648 0.56949949 0.25511871
  0.58272204]
 [0.3568503  0.48144248 0.98740642 0.46168917 0.36155611 0.59656115
  0.4007678 ]
 [0.38226808 0.54382574 0.4963156  0.80423689 0.28030275 0.44156927
  0.26038199]
 [0.35127304 0.09716665 0.4767984  0.88613249 0.74959676 0.5071329
  0.36860786]
 [0.68105873 0.2321942  0.08475341 0.89368928 0.9153321  0.57033302
  0.27252794]]
сума стовпчиків матриці
[3.67323896 3.3983538  4.42430596 4.43771457 3.38343527 3.28684337
 3.07034336]


Висновок: отримав навички розробки матриць та взаємодії з ними. Завдання були доволі легкими, проте в завданні 12, чомусь неправильно рахується сума матриці